In [2]:
import numpy as np

Scalars

In [3]:
s = np.array(5)
s

array(5)

In [4]:
s.shape

()

In [5]:
x = s + 3
x

8

Vectors

In [6]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [7]:
v.shape

(3,)

In [9]:
el_0 = v[0]
el_1 = v[1]
el_0, el_1

(1, 2)

In [10]:
v[1:]

array([2, 3])

Matrices

In [11]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
m.shape

(3, 3)

In [13]:
m[2][2]

9

Tensors

In [16]:
t = np.array([[[[1], [2]], [[3], [4]], [[5], [6]]], [[[7], [8]],\
               [[9], [10]], [[11], [12]]], [[[13], [14]], [[15], [16]], [[17], [17]]]])
t.shape

(3, 3, 2, 1)

There are 3 external components. Each component is made of other 3 components. Each of them made of 2 components, each made of 1 component. 

Let's access the element equal to 5

In [19]:
y = t[0][2][0][0]
y

5

Reshape - Changing Shape

In [20]:
v1 = np.array([1, 2, 3, 4])
v1. shape

(4,)

In [21]:
v2 = v1.reshape(4, 1)
v2

array([[1],
       [2],
       [3],
       [4]])

In [22]:
x1 = v1[None, :]
x1

array([[1, 2, 3, 4]])

In [25]:
x2 = v1[:, None]
x2

array([[1],
       [2],
       [3],
       [4]])

Addition

In [26]:
x = np.array([1, 2, 3, 4, 5])
x1 = x + 5
x1

array([ 6,  7,  8,  9, 10])

Multiplication by a scalar

In [27]:
x3 = np.multiply(x, 5)
x3

array([ 5, 10, 15, 20, 25])

In [28]:
# Useful to reset matrix
m *= 0
m

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Element-wise Multiplication

In [3]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
n = m * 0.25
n

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ]])

In [5]:
m * n

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [6]:
np.multiply(m, n)

array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

Matrix product

In [9]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
a.shape, b.shape

((2, 4), (4, 3))

In [13]:
c = np.matmul(a, b)
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [14]:
a = np.arange(3*4*5*6)
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [16]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
a

array([[[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]],


       [[[120, 121, 122, 123, 124, 125],
         [126, 127, 128, 129, 130, 131],
         [132, 133, 134, 135, 136, 137],
         [138, 139, 140, 141, 142, 143],
      

In [17]:
b = np.arange(3*4*5*6)[::-1]
b

array([359, 358, 357, 356, 355, 354, 353, 352, 351, 350, 349, 348, 347,
       346, 345, 344, 343, 342, 341, 340, 339, 338, 337, 336, 335, 334,
       333, 332, 331, 330, 329, 328, 327, 326, 325, 324, 323, 322, 321,
       320, 319, 318, 317, 316, 315, 314, 313, 312, 311, 310, 309, 308,
       307, 306, 305, 304, 303, 302, 301, 300, 299, 298, 297, 296, 295,
       294, 293, 292, 291, 290, 289, 288, 287, 286, 285, 284, 283, 282,
       281, 280, 279, 278, 277, 276, 275, 274, 273, 272, 271, 270, 269,
       268, 267, 266, 265, 264, 263, 262, 261, 260, 259, 258, 257, 256,
       255, 254, 253, 252, 251, 250, 249, 248, 247, 246, 245, 244, 243,
       242, 241, 240, 239, 238, 237, 236, 235, 234, 233, 232, 231, 230,
       229, 228, 227, 226, 225, 224, 223, 222, 221, 220, 219, 218, 217,
       216, 215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204,
       203, 202, 201, 200, 199, 198, 197, 196, 195, 194, 193, 192, 191,
       190, 189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 17

In [18]:
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
b

array([[[[359, 358, 357],
         [356, 355, 354],
         [353, 352, 351],
         [350, 349, 348],
         [347, 346, 345],
         [344, 343, 342]],

        [[341, 340, 339],
         [338, 337, 336],
         [335, 334, 333],
         [332, 331, 330],
         [329, 328, 327],
         [326, 325, 324]],

        [[323, 322, 321],
         [320, 319, 318],
         [317, 316, 315],
         [314, 313, 312],
         [311, 310, 309],
         [308, 307, 306]],

        [[305, 304, 303],
         [302, 301, 300],
         [299, 298, 297],
         [296, 295, 294],
         [293, 292, 291],
         [290, 289, 288]]],


       [[[287, 286, 285],
         [284, 283, 282],
         [281, 280, 279],
         [278, 277, 276],
         [275, 274, 273],
         [272, 271, 270]],

        [[269, 268, 267],
         [266, 265, 264],
         [263, 262, 261],
         [260, 259, 258],
         [257, 256, 255],
         [254, 253, 252]],

        [[251, 250, 249],
         [248, 247, 246]

In [19]:
np.dot(a, b)[2,3,2,1,2,2]

499128

In [21]:
sum(a[2,3,2,:] * b[1,2,:,2])

499128

Transpose

In [22]:
m = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

NumpyExam

In [49]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = (np.array([inputs]))
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    min_el = np.min(input_array)
    inputs_minus_min = input_array - min_el

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    max_el = np.max(inputs_minus_min)
    inputs_div_max = inputs_minus_min / max_el

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    compatible = (m1.shape[1] == m2.shape[0]) 
    swap = (m2.shape[1] == m1.shape[0])
    if not(compatible) and not(swap):
        return compatible

    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if swap:
        mat_prod = np.matmul(m2, m1)
    else:
        mat_prod = np.matmul(m1, m2)
    return mat_prod
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return sum(values) / len(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
